package dev.resolvedor.pos.sales;

import dev.resolvedor.pos.inventory.management.*;
import com.unicenta.basic.BasicException;
import com.unicenta.data.loader.LocalRes;
import com.unicenta.data.loader.SentenceList;
import com.unicenta.data.user.ListProvider;
import com.unicenta.data.user.ListProviderCreator;
import com.unicenta.format.Formats;
import com.unicenta.pos.forms.AppLocal;
import com.unicenta.pos.forms.DataLogicSales;
import com.unicenta.pos.sales.TaxesLogic;
import com.unicenta.pos.ticket.ProductInfoExt;
import com.unicenta.pos.ticket.TaxInfo;
import dev.resolvedor.util.StringUtils;
import dev.resolvedor.util.Read;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author Jorge Luis
 * @web https://joguenco.dev
 * @mail jorgeluis@joguenco.dev
 */
@Slf4j
public class ProductFinder extends javax.swing.JDialog {

    private ProductInfoExt selectedProduct;
    private VolumeDiscountInfo selectedDiscount;
    private TaxInfo tax;

    private DataLogicSales dlSales;

    private ListProvider lpr;

    private TaxesLogic taxeslogic;

    private SentenceList sentTax;

    public static final int RET_CANCEL = 0;
    public static final int RET_OK = 1;

    public ProductFinder(DataLogicSales dlSales, java.awt.Frame parent) {
        super(parent, true);
        initComponents();

        this.dlSales = dlSales;

        // Render in finder list
        jListProducts.setCellRenderer(new ProductRenderer());

        sentTax = dlSales.getTaxList();
        java.util.List<TaxInfo> taxlist;
        try {
            taxlist = sentTax.list();
            taxeslogic = new TaxesLogic(taxlist);
        } catch (BasicException ex) {
            log.error(ProductFinder.class.getName() + " " + ex.getMessage());
        }

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    public VolumeDiscountInfo getSelectedDiscount() {
        return selectedDiscount;
    }

    public TaxInfo getTax() {
        return tax;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        panelFinder = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        cmdFindProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProducts = new javax.swing.JList();
        lblProduct = new javax.swing.JLabel();
        panelFeatures = new javax.swing.JPanel();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblDiscount = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblPriceFinal = new javax.swing.JLabel();
        txtPriceFinal = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        panelFinder.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        lblName.setText(bundle.getString("label.name")); // NOI18N
        lblName.setPreferredSize(new java.awt.Dimension(120, 26));

        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });

        cmdFindProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/search24.png"))); // NOI18N
        cmdFindProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFindProductActionPerformed(evt);
            }
        });

        jScrollPane1.setMaximumSize(new java.awt.Dimension(260, 132));

        jListProducts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProducts.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListProductsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListProducts);

        lblProduct.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProduct.setText(bundle.getString("label.stockproduct")); // NOI18N
        lblProduct.setPreferredSize(new java.awt.Dimension(120, 26));

        javax.swing.GroupLayout panelFinderLayout = new javax.swing.GroupLayout(panelFinder);
        panelFinder.setLayout(panelFinderLayout);
        panelFinderLayout.setHorizontalGroup(
            panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdFindProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFinderLayout.setVerticalGroup(
            panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdFindProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFeatures.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("button.discount"))); // NOI18N

        lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQuantity.setText(bundle.getString("label.units2")); // NOI18N
        lblQuantity.setPreferredSize(new java.awt.Dimension(120, 26));

        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQuantity.setText("1");

        lblDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiscount.setText(bundle.getString("button.discount")); // NOI18N
        lblDiscount.setPreferredSize(new java.awt.Dimension(120, 26));

        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDiscount.setText("0");
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });

        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrice.setText(bundle.getString("label.pricetax")); // NOI18N
        lblPrice.setPreferredSize(new java.awt.Dimension(120, 26));

        txtPrice.setEditable(false);
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrice.setText("0");

        lblPriceFinal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPriceFinal.setText(bundle.getString("label.pricetax.final")); // NOI18N
        lblPriceFinal.setPreferredSize(new java.awt.Dimension(120, 26));

        txtPriceFinal.setEditable(false);
        txtPriceFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPriceFinal.setText("0");

        javax.swing.GroupLayout panelFeaturesLayout = new javax.swing.GroupLayout(panelFeatures);
        panelFeatures.setLayout(panelFeaturesLayout);
        panelFeaturesLayout.setHorizontalGroup(
            panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFeaturesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFeaturesLayout.createSequentialGroup()
                        .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFeaturesLayout.createSequentialGroup()
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFeaturesLayout.createSequentialGroup()
                        .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFeaturesLayout.createSequentialGroup()
                        .addComponent(lblPriceFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPriceFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFeaturesLayout.setVerticalGroup(
            panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFeaturesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPriceFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPriceFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFinder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(panelFeatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFinder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFeatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        if (!validateData()) {
            return;
        }

        tax = taxeslogic.getTaxInfo(selectedProduct.getTaxCategoryID(), null);

        selectedDiscount = new VolumeDiscountInfo();
        selectedDiscount.setProduct(selectedProduct);
        selectedDiscount.setMinimumQuantity(Double.parseDouble(txtQuantity.getText()));
        selectedDiscount.setValue(Double.parseDouble(txtDiscount.getText()));

        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private boolean validateData() {
        if (selectedProduct == null) {
            JOptionPane.showMessageDialog(this, AppLocal.getIntString("message.noproduct"), AppLocal.getIntString("label.stockproduct"), JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!StringUtils.isNumber(txtQuantity.getText().trim())) {
            JOptionPane.showMessageDialog(this, LocalRes.getIntString("message.numericamount"), AppLocal.getIntString("label.units2"), JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            var validNumber = Double.parseDouble(txtQuantity.getText().trim());
            if (validNumber <= 0) {
                JOptionPane.showMessageDialog(this, LocalRes.getIntString("exception.nonegativenumberorzero"), AppLocal.getIntString("label.units2"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        if (!StringUtils.isNumber(txtDiscount.getText().trim())) {
            JOptionPane.showMessageDialog(this, LocalRes.getIntString("message.numericamount"), AppLocal.getIntString("button.discount"), JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            var validNumber = Double.parseDouble(txtDiscount.getText().trim());
            if (validNumber <= 0) {
                JOptionPane.showMessageDialog(this, LocalRes.getIntString("exception.nonegativenumberorzero"), AppLocal.getIntString("button.discount"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        if (Read.currency(txtPrice.getText().trim()) == null) {
            JOptionPane.showMessageDialog(this, LocalRes.getIntString("message.numericTotal"), AppLocal.getIntString("label.total"), JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            var validNumber = Read.currency(txtPrice.getText().trim());
            if (validNumber < 0) {
                JOptionPane.showMessageDialog(this, LocalRes.getIntString("exception.nonegativenumberorzero"), AppLocal.getIntString("label.total"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        return true;
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        findProduct();
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void findProduct() {
        lpr = new ListProviderCreator(dlSales.getProductListByName(txtProductName.getText()));

        try {
            jListProducts.setModel(new ProductFinder.MyListData(lpr.loadData()));
            if (jListProducts.getModel().getSize() > 0) {
                jListProducts.setSelectedIndex(0);
                jListProducts.requestFocus();
            }
        } catch (BasicException e) {
        }
    }

    private void jListProductsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListProductsValueChanged
        loadProduct();
        calculatePriceFinal();
    }//GEN-LAST:event_jListProductsValueChanged

    private void cmdFindProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFindProductActionPerformed
        findProduct();
    }//GEN-LAST:event_cmdFindProductActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        calculatePriceFinal();
        txtPrice.requestFocus();
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void calculatePriceFinal() {
        if (selectedProduct != null) {
            tax = taxeslogic.getTaxInfo(selectedProduct.getTaxCategoryID(), null);
            double taxValue = tax.getRate() + 1;
            var priceSell = selectedProduct.getPriceSell();

            double priceSellFinal = priceSell - (priceSell * (Double.parseDouble(txtDiscount.getText().trim()) / 100));
            priceSellFinal = priceSellFinal * taxValue;
            txtPriceFinal.setText(Formats.CURRENCY.formatValue(priceSellFinal));            
        }
    }
    private void loadProduct() {
        selectedProduct = (ProductInfoExt) jListProducts.getSelectedValue();

        if (selectedProduct != null) {
            tax = taxeslogic.getTaxInfo(selectedProduct.getTaxCategoryID(), null);

            double taxValue = tax.getRate() + 1;
            txtPrice.setText(Formats.CURRENCY.formatValue(
                    selectedProduct.getPriceSell() * taxValue
            ));
        }
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    private static class MyListData extends javax.swing.AbstractListModel {

        private final java.util.List m_data;

        public MyListData(java.util.List data) {
            m_data = data;
        }

        @Override
        public Object getElementAt(int index) {
            return m_data.get(index);
        }

        @Override
        public int getSize() {
            return m_data.size();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cmdFindProduct;
    private javax.swing.JList jListProducts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPriceFinal;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel panelFeatures;
    private javax.swing.JPanel panelFinder;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPriceFinal;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
