package dev.resolvedor.pos.inventory.management;

import com.unicenta.basic.BasicException;
import com.unicenta.beans.DateUtils;
import com.unicenta.beans.JCalendarDialog;
import com.unicenta.data.user.ListProvider;
import com.unicenta.data.user.ListProviderCreator;
import com.unicenta.format.Formats;
import com.unicenta.pos.forms.AppLocal;
import com.unicenta.pos.forms.AppView;
import com.unicenta.pos.forms.DataLogicSales;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author Jorge Luis
 * @web https://joguenco.dev
 * @mail jorgeluis@joguenco.dev
 */
@Slf4j
public class PurchaseFinderDialog extends javax.swing.JDialog {

    private DataLogicPurchase dlPurchase;
    private DataLogicSales dlSales;
    private PurchaseInfo selectedPurchase;
    private ListProvider lpr;

    public static final int RET_CANCEL = 0;
    public static final int RET_OK = 1;

    public PurchaseFinderDialog(AppView app, java.awt.Frame parent) {
        super(parent, true);
        initComponents();

        dlPurchase = (DataLogicPurchase) app.getBean("dev.resolvedor.pos.inventory.management.DataLogicPurchase");
        dlSales = (DataLogicSales) app.getBean("com.unicenta.pos.forms.DataLogicSales");

        txtStartDate.setText(
                Formats.DATE.formatValue(DateUtils.getFirstDayOfMonth())
        );

        txtEndDate.setText(
                Formats.DATE.formatValue(DateUtils.getTodayMinutes())
        );

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    public PurchaseInfo getSelectedPurchase() {
        return selectedPurchase;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        panelFinder = new javax.swing.JPanel();
        lblPurchase = new javax.swing.JLabel();
        txtPurchase = new javax.swing.JTextField();
        cmdFinder = new javax.swing.JButton();
        lblDates = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        cmdStartDate = new javax.swing.JButton();
        txtEndDate = new javax.swing.JTextField();
        cmdEndDate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPurchases = new javax.swing.JList();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(this::okButtonActionPerformed);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        lblPurchase.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        lblPurchase.setText(bundle.getString("Menu.Suppliers.Reports.Purchases")); // NOI18N
        lblPurchase.setPreferredSize(new java.awt.Dimension(120, 36));

        txtPurchase.setPreferredSize(new java.awt.Dimension(330, 36));
        txtPurchase.addActionListener(this::txtPurchaseActionPerformed);

        cmdFinder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/search24.png"))); // NOI18N
        cmdFinder.setPreferredSize(new java.awt.Dimension(36, 36));
        cmdFinder.addActionListener(this::cmdFinderActionPerformed);

        lblDates.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDates.setText(bundle.getString("label.datestitle")); // NOI18N
        lblDates.setPreferredSize(new java.awt.Dimension(120, 36));

        txtStartDate.setPreferredSize(new java.awt.Dimension(120, 36));

        cmdStartDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/date.png"))); // NOI18N
        cmdStartDate.setPreferredSize(new java.awt.Dimension(36, 36));
        cmdStartDate.addActionListener(this::cmdStartDateActionPerformed);

        txtEndDate.setPreferredSize(new java.awt.Dimension(120, 36));

        cmdEndDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/date.png"))); // NOI18N
        cmdEndDate.setPreferredSize(new java.awt.Dimension(36, 36));
        cmdEndDate.addActionListener(this::cmdEndDateActionPerformed);

        jListPurchases.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jListPurchases.addListSelectionListener(this::jListPurchasesValueChanged);
        jScrollPane1.setViewportView(jListPurchases);

        javax.swing.GroupLayout panelFinderLayout = new javax.swing.GroupLayout(panelFinder);
        panelFinder.setLayout(panelFinderLayout);
        panelFinderLayout.setHorizontalGroup(
            panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelFinderLayout.createSequentialGroup()
                        .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFinderLayout.createSequentialGroup()
                                .addComponent(lblPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdFinder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFinderLayout.createSequentialGroup()
                                .addComponent(lblDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFinderLayout.setVerticalGroup(
            panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdFinder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmdStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 432, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(panelFinder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFinder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (selectedPurchase == null) {
            return;
        }

        try {
            selectedPurchase = dlPurchase.loadPurchase(selectedPurchase.getId(), dlSales);
        } catch (BasicException ex) {
            log.error(PurchaseFinderDialog.class.getName() + " okButtonActionPerformed " + ex);
        }

        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void cmdFinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFinderActionPerformed
        findPurchase();
    }//GEN-LAST:event_cmdFinderActionPerformed

    private void txtPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurchaseActionPerformed
        findPurchase();
    }//GEN-LAST:event_txtPurchaseActionPerformed

    private void jListPurchasesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListPurchasesValueChanged
        selectedPurchase = (PurchaseInfo) jListPurchases.getSelectedValue();
    }//GEN-LAST:event_jListPurchasesValueChanged

    private void cmdStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStartDateActionPerformed
        setDate(txtStartDate);
    }//GEN-LAST:event_cmdStartDateActionPerformed

    private void cmdEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEndDateActionPerformed
        setDate(txtEndDate);
    }//GEN-LAST:event_cmdEndDateActionPerformed

    private void setDate(javax.swing.JTextField txtField) {
        Date date;
        try {
            date = (Date) Formats.DATE.parseValue(txtField.getText());
        } catch (BasicException e) {
            date = null;
        }
        date = JCalendarDialog.showCalendarTime(this, date);
        if (date != null) {
            txtField.setText(Formats.DATE.formatValue(date));
        }
    }

    private void findPurchase() {
        Date startDate = null;
        Date endDate = null;
        try {
            startDate = (Date) Formats.DATE.parseValue(txtStartDate.getText());
            endDate = (Date) Formats.DATE.parseValue(txtEndDate.getText());
        } catch (BasicException ex) {
            JOptionPane.showMessageDialog(this, AppLocal.getIntString("label.datestitle"), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {

            lpr = new ListProviderCreator(
                    dlPurchase.getPurchaseListByData(
                            startDate,
                            endDate,
                            txtPurchase.getText()
                    )
            );

            jListPurchases.setModel(new PurchaseFinderDialog.MyListData(lpr.loadData()));
            if (jListPurchases.getModel().getSize() > 0) {
                jListPurchases.setSelectedIndex(0);
                jListPurchases.requestFocus();
            }
        } catch (BasicException ex) {
            log.error(PurchaseFinderDialog.class.getName() + " cmdFinderActionPerformed " + ex);
        }
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    private static class MyListData extends javax.swing.AbstractListModel {

        private final java.util.List m_data;

        public MyListData(java.util.List data) {
            m_data = data;
        }

        @Override
        public Object getElementAt(int index) {
            return m_data.get(index);
        }

        @Override
        public int getSize() {
            return m_data.size();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cmdEndDate;
    private javax.swing.JButton cmdFinder;
    private javax.swing.JButton cmdStartDate;
    private javax.swing.JList jListPurchases;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDates;
    private javax.swing.JLabel lblPurchase;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel panelFinder;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtPurchase;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
