package dev.resolvedor.pos.inventory.management;

import com.unicenta.basic.BasicException;
import com.unicenta.data.gui.ComboBoxValModel;
import com.unicenta.data.loader.LocalRes;
import com.unicenta.data.loader.SentenceList;
import com.unicenta.data.user.ListProvider;
import com.unicenta.data.user.ListProviderCreator;
import com.unicenta.format.Formats;
import com.unicenta.pos.forms.AppLocal;
import com.unicenta.pos.forms.AppView;
import com.unicenta.pos.forms.DataLogicSales;
import com.unicenta.pos.sales.TaxesLogic;
import com.unicenta.pos.ticket.ProductInfoExt;
import com.unicenta.pos.ticket.TaxInfo;
import dev.resolvedor.util.StringUtils;
import dev.resolvedor.pos.inventory.lot.DataLogicLot;
import dev.resolvedor.util.Read;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import lombok.extern.slf4j.Slf4j;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Jorge Luis
 * @web https://joguenco.dev
 * @mail jorgeluis@joguenco.dev
 */
@Slf4j
public class PurchaseProductDialog extends javax.swing.JDialog {

    private ProductInfoExt selectedProduct;
    private TaxInfo tax;

    private DataLogicLot dlLot;
    private DataLogicSales dlSales;

    private ComboBoxValModel modelLot;
    private ComboBoxValModel modelTaxSupport;

    private ListProvider lpr;

    private TaxesLogic taxeslogic;

    private SentenceList sentTax;

    public static final int RET_CANCEL = 0;
    public static final int RET_OK = 1;

    public PurchaseProductDialog(AppView app, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        dlLot = (DataLogicLot) app.getBean("dev.resolvedor.pos.inventory.lot.DataLogicLot");
        dlSales = (DataLogicSales) app.getBean("com.unicenta.pos.forms.DataLogicSales");

        loadTaxSupports(app);

        // Render in finder list
        jListProducts.setCellRenderer(new ProductRenderer());

        sentTax = dlSales.getTaxList();
        java.util.List<TaxInfo> taxlist;
        try {
            taxlist = sentTax.list();
            taxeslogic = new TaxesLogic(taxlist);
        } catch (BasicException ex) {
            log.error(PurchaseProductDialog.class.getName() + " " + ex.getMessage());
        }

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    public ProductInfoExt getProduct() {
        return selectedProduct;
    }

    public TaxInfo getTax() {
        return tax;
    }

    /**
     * El sustento tributario elegido para este producto.
     */
    public String getTaxSupport() {
        return modelTaxSupport == null || modelTaxSupport.getSelectedKey() == null
                ? null : modelTaxSupport.getSelectedKey().toString();
    }

    /**
     * Precarga el sustento con el de la cabecera de la compra.
     *
     * Es solo una ayuda: casi siempre todos los items llevan el mismo, asi que
     * viene puesto y el usuario solo lo cambia en los que difieren.
     */
    public void setTaxSupport(String taxSupport) {
        if (modelTaxSupport != null) {
            modelTaxSupport.setSelectedKey(taxSupport);
        }
    }

    private void loadTaxSupports(AppView app) {
        try {
            var dlPurchase = (DataLogicPurchase) app.getBean(
                    "dev.resolvedor.pos.inventory.management.DataLogicPurchase");

            modelTaxSupport = new ComboBoxValModel(dlPurchase.getTaxSupportList().list());
            cboTaxSupport.setModel(modelTaxSupport);
            modelTaxSupport.setSelectedKey(null);
        } catch (Exception ex) {
            log.error(PurchaseProductDialog.class.getName() + " " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTaxSupport = new javax.swing.JPanel();
        lblTaxSupport = new javax.swing.JLabel();
        cboTaxSupport = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        panelFinder = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        cmdFindProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProducts = new javax.swing.JList();
        lblProduct = new javax.swing.JLabel();
        panelFeatures = new javax.swing.JPanel();
        lblQuantity = new javax.swing.JLabel();
        txtQuantiy = new javax.swing.JTextField();
        lblLot = new javax.swing.JLabel();
        cboLot = new javax.swing.JComboBox<>();
        lblTotalCost = new javax.swing.JLabel();
        txtTotalCost = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelTaxSupport.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTaxSupport.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaxSupport.setText(AppLocal.getIntString("label.taxSupport")); // NOI18N
        lblTaxSupport.setPreferredSize(new java.awt.Dimension(120, 26));

        javax.swing.GroupLayout panelTaxSupportLayout = new javax.swing.GroupLayout(panelTaxSupport);
        panelTaxSupport.setLayout(panelTaxSupportLayout);
        panelTaxSupportLayout.setHorizontalGroup(
            panelTaxSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaxSupportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaxSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboTaxSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTaxSupportLayout.setVerticalGroup(
            panelTaxSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaxSupportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTaxSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTaxSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        panelFinder.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        lblName.setText(bundle.getString("label.name")); // NOI18N
        lblName.setPreferredSize(new java.awt.Dimension(120, 26));

        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });

        cmdFindProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/search24.png"))); // NOI18N
        cmdFindProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFindProductActionPerformed(evt);
            }
        });

        jScrollPane1.setMaximumSize(new java.awt.Dimension(260, 132));

        jListProducts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProducts.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListProductsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListProducts);

        lblProduct.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProduct.setText(bundle.getString("label.stockproduct")); // NOI18N
        lblProduct.setPreferredSize(new java.awt.Dimension(120, 26));

        javax.swing.GroupLayout panelFinderLayout = new javax.swing.GroupLayout(panelFinder);
        panelFinder.setLayout(panelFinderLayout);
        panelFinderLayout.setHorizontalGroup(
            panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdFindProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFinderLayout.setVerticalGroup(
            panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdFindProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFeatures.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQuantity.setText(bundle.getString("label.units2")); // NOI18N
        lblQuantity.setPreferredSize(new java.awt.Dimension(120, 26));

        txtQuantiy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQuantiy.setText("1");

        lblLot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLot.setText(bundle.getString("label.lot")); // NOI18N
        lblLot.setPreferredSize(new java.awt.Dimension(120, 26));

        lblTotalCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalCost.setText(bundle.getString("label.total")); // NOI18N
        lblTotalCost.setPreferredSize(new java.awt.Dimension(120, 26));

        txtTotalCost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalCost.setText("0");

        javax.swing.GroupLayout panelFeaturesLayout = new javax.swing.GroupLayout(panelFeatures);
        panelFeatures.setLayout(panelFeaturesLayout);
        panelFeaturesLayout.setHorizontalGroup(
            panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFeaturesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFeaturesLayout.createSequentialGroup()
                        .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantiy, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFeaturesLayout.createSequentialGroup()
                        .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLot, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFeaturesLayout.setVerticalGroup(
            panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFeaturesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantiy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLot, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFeaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFinder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(panelFeatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTaxSupport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFinder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTaxSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        if (!validateData()) {
            return;
        }

        tax = taxeslogic.getTaxInfo(selectedProduct.getTaxCategoryID(), null);

        selectedProduct.setQuantity(Double.parseDouble(txtQuantiy.getText()));
        selectedProduct.setTotalCost(Read.currency(txtTotalCost.getText().trim()));

        double costWithTax = selectedProduct.getTotalCost() / selectedProduct.getQuantity();
        double taxValue = tax.getRate() + 1;
        selectedProduct.setPriceBuy(costWithTax / taxValue);
        selectedProduct.setLot(modelLot.getSelectedKey().toString());
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private boolean validateData() {
        // El SRI exige el sustento por item, no por documento, asi que sin el
        // la linea no sirve para armar la retencion.
        if (getTaxSupport() == null) {
            JOptionPane.showMessageDialog(this,
                    AppLocal.getIntString("message.fillallfields"),
                    AppLocal.getIntString("label.taxSupport"),
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!StringUtils.isNumber(txtQuantiy.getText().trim())) {
            JOptionPane.showMessageDialog(this, LocalRes.getIntString("message.numericamount"), AppLocal.getIntString("label.units2"), JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            var validNumber = Double.parseDouble(txtQuantiy.getText().trim());
            if (validNumber <= 0) {
                JOptionPane.showMessageDialog(this, LocalRes.getIntString("exception.nonegativenumberorzero"), AppLocal.getIntString("label.units2"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        if (selectedProduct == null) {
            JOptionPane.showMessageDialog(this, AppLocal.getIntString("message.noproduct"), AppLocal.getIntString("label.stockproduct"), JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (modelLot.getSelectedKey() == null) {
            JOptionPane.showMessageDialog(this, LocalRes.getIntString("exception.noLot"), AppLocal.getIntString("label.lot"), JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (Read.currency(txtTotalCost.getText().trim()) == null) {
            JOptionPane.showMessageDialog(this, LocalRes.getIntString("message.numericTotal"), AppLocal.getIntString("label.total"), JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            var validNumber = Read.currency(txtTotalCost.getText().trim());
            if (validNumber < 0) {
                JOptionPane.showMessageDialog(this, LocalRes.getIntString("exception.nonegativenumberorzero"), AppLocal.getIntString("label.total"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        try {
            if (dlSales.isProductBundle(selectedProduct.getID())) {
                JOptionPane.showMessageDialog(this, LocalRes.getIntString("message.product.bundle.purchase"), AppLocal.getIntString("label.stockproduct"), JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (BasicException ex) {
            log.error(PurchaseProductDialog.class.getName() + " isProductBundle " + ex);
            return false;
        }

        return true;
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        findProduct();
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void findProduct() {
        lpr = new ListProviderCreator(dlSales.getProductListByName(txtProductName.getText()));

        try {
            jListProducts.setModel(new PurchaseProductDialog.MyListData(lpr.loadData()));
            if (jListProducts.getModel().getSize() > 0) {
                jListProducts.setSelectedIndex(0);
                jListProducts.requestFocus();
            }
        } catch (BasicException e) {
        }
    }

    private void jListProductsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListProductsValueChanged
        loadLotsOfProduct();
    }//GEN-LAST:event_jListProductsValueChanged

    private void cmdFindProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFindProductActionPerformed
        findProduct();
    }//GEN-LAST:event_cmdFindProductActionPerformed

    private void loadLotsOfProduct() {
        selectedProduct = (ProductInfoExt) jListProducts.getSelectedValue();

        if (selectedProduct != null) {
            try {
                modelLot = new ComboBoxValModel(
                        dlLot.getLotList(selectedProduct.getID()).list()
                );
                cboLot.setModel(modelLot);
                modelLot.setSelectedFirst();

                txtTotalCost.setText(Formats.CURRENCY.formatValue(selectedProduct.getPriceBuy()));
            } catch (BasicException ex) {
                log.error(PurchaseProductDialog.class.getName() + " " + ex.getMessage());
                modelLot = new ComboBoxValModel();
                cboLot.setModel(modelLot);
            }
        } else {
            modelLot = new ComboBoxValModel();
            cboLot.setModel(modelLot);
        }
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    private static class MyListData extends javax.swing.AbstractListModel {

        private final java.util.List m_data;

        public MyListData(java.util.List data) {
            m_data = data;
        }

        @Override
        public Object getElementAt(int index) {
            return m_data.get(index);
        }

        @Override
        public int getSize() {
            return m_data.size();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cboLot;
    private javax.swing.JButton cmdFindProduct;
    private javax.swing.JList jListProducts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLot;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JComboBox<String> cboTaxSupport;
    private javax.swing.JLabel lblTaxSupport;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel panelFeatures;
    private javax.swing.JPanel panelFinder;
    private javax.swing.JPanel panelTaxSupport;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantiy;
    private javax.swing.JTextField txtTotalCost;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
