package dev.resolvedor.pos.inventory.lot;

import com.unicenta.basic.BasicException;
import com.unicenta.data.gui.ComboBoxValModel;
import com.unicenta.data.loader.LocalRes;
import com.unicenta.data.loader.SentenceList;
import com.unicenta.format.Formats;
import com.unicenta.pos.forms.AppLocal;
import com.unicenta.pos.forms.AppView;
import dev.resolvedor.util.ColorRenderer;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import lombok.extern.slf4j.Slf4j;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Jorge Luis
 * @web https://joguenco.dev
 * @mail jorgeluis@joguenco.dev
 */
@Slf4j
public class ProductLotDialog extends JDialog {

    private Object lotId;
    private DataLogicLot dlLot;
    private SentenceList sentenceProduct;
    private ComboBoxValModel modelProduct;

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form ProductLotDialog
     * @param app
     * @param lotId
     * @param parent
     */
    public ProductLotDialog(AppView app, Object lotId, java.awt.Frame parent) {
        super(parent, true);
        initComponents();

        this.lotId = lotId;
        dlLot = (DataLogicLot) app.getBean("dev.resolvedor.pos.inventory.lot.DataLogicLot");

        AutoCompleteDecorator.decorate(cboProduct);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cboProduct = new javax.swing.JComboBox<>();
        cmdAdd = new javax.swing.JButton();
        cmdDelete = new javax.swing.JButton();
        cmdStatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        setTitle(bundle.getString("Menu.Products")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cmdAdd.setText(bundle.getString("label.add")); // NOI18N
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        cmdDelete.setText(bundle.getString("label.delete")); // NOI18N
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });

        cmdStatus.setText(bundle.getString("label.Status")); // NOI18N
        cmdStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStatusActionPerformed(evt);
            }
        });

        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Expiration", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableProducts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAdd)
                    .addComponent(cmdDelete)
                    .addComponent(cmdStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        doClose(RET_CANCEL);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        sentenceProduct = dlLot.getProductList();
        try {
            modelProduct = new ComboBoxValModel(sentenceProduct.list());
            cboProduct.setModel(modelProduct);

            var products = dlLot.getLotProductList(lotId.toString());
            loadTable(tableProducts, products);
        } catch (BasicException ex) {
            log.error(ProductLotDialog.class.getName() + " " + ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        if (modelProduct.getSelectedKey() == null) {
            return;
        }

        try {
            dlLot.saveLotProduct(
                    lotId.toString(),
                    modelProduct.getSelectedKey().toString()
            );
            var products = dlLot.getLotProductList(lotId.toString());
            loadTable(tableProducts, products);
        } catch (BasicException ex) {
            JOptionPane.showMessageDialog(this, LocalRes.getIntString("exception.noinsert"));
            log.error(ProductLotDialog.class.getName() + " " + ex.getMessage());
        }
    }//GEN-LAST:event_cmdAddActionPerformed

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        if (tableProducts.getSelectedRow() >= 0) {
            try {
                int input = JOptionPane.showConfirmDialog(this, AppLocal.getIntString("message.deletelineyes"),
                        AppLocal.getIntString("label.deleteline"), JOptionPane.YES_NO_OPTION);

                if (input == 0) {
                    var productId = tableProducts
                            .getValueAt(tableProducts.getSelectedRow(), 0).toString();
                    dlLot.deleteLotProduct(lotId.toString(), productId);

                    var products = dlLot.getLotProductList(lotId.toString());
                    loadTable(tableProducts, products);
                }
            } catch (BasicException ex) {
                JOptionPane.showMessageDialog(this, LocalRes.getIntString("exception.nodelete"));
                log.error(ProductLotDialog.class.getName() + " " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_cmdDeleteActionPerformed

    private void cmdStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStatusActionPerformed

        if (tableProducts.getSelectedRow() >= 0) {
            try {
                var productId = tableProducts
                        .getValueAt(tableProducts.getSelectedRow(), 0).toString();
                dlLot.updateStatusLotProduct(lotId.toString(), productId);
                var products = dlLot.getLotProductList(lotId.toString());
                loadTable(tableProducts, products);
            } catch (BasicException ex) {
                JOptionPane.showMessageDialog(this, LocalRes.getIntString("exception.noupdate"));
                log.error(ProductLotDialog.class.getName() + " cmdStatusActionPerformed " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_cmdStatusActionPerformed

    private void loadTable(JTable table, List<ProductLotInfo> products) {

        String[] columnName = {"ProductId", "Producto", "Expiración", "Estado", "Stock"};

        table.setModel(new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(columnName);

        for (ProductLotInfo product : products) {
            model.addRow(new Object[]{
                product.getProduct(),
                product.getProductName(),
                Formats.DATE.formatValue(product.getExpirationDate()),
                product.getStatus(),
                product.getStock()
            });
        }

        lookTable(table);
    }

    private void lookTable(JTable table) {

        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);

        table.getColumnModel().getColumn(0).setPreferredWidth(0);
        table.getColumnModel().getColumn(1).setPreferredWidth(180);
        table.getColumnModel().getColumn(2).setPreferredWidth(120);
        table.getColumnModel().getColumn(3).setPreferredWidth(90);
        table.getColumnModel().getColumn(4).setPreferredWidth(90);        
        table.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);

        ColorRenderer colorRenderer = new ColorRenderer();
        table.setDefaultRenderer(Object.class, colorRenderer);                
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboProduct;
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JTable tableProducts;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
