//    Mestizo Pos - Touch Friendly Point Of Sale
//    https://joguenco.dev
//
//    Mestizo Pos is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Mestizo Pos is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Mestizo Pos.  If not, see <http://www.gnu.org/licenses/>.
package dev.joguenco.pos.taxpayer;

import com.unicenta.basic.BasicException;
import com.unicenta.data.loader.TableDefinition;
import com.unicenta.pos.forms.AppConfig;
import com.unicenta.pos.forms.AppLocal;
import com.unicenta.pos.forms.AppView;
import com.unicenta.pos.forms.BeanFactoryApp;
import com.unicenta.pos.forms.BeanFactoryException;
import com.unicenta.pos.forms.JPanelView;
import dev.joguenco.error.ErrorMessage;
import java.io.File;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author jorgeluis
 */
@Slf4j
public class Taxpayer extends JPanel implements JPanelView, BeanFactoryApp {

    private AppView app;
    private DataLogicTaxpayer dlTaxpayer;
    private TableDefinition tdTaxpayer;
    private String country;

    public Taxpayer() {
        initComponents();
        final var config = new AppConfig(new File((System.getProperty("user.home")), AppLocal.APP_ID + ".properties"));
        config.load();
        country = config.getProperty("user.country");
    }

    @Override
    public String getTitle() {
        return AppLocal.getIntString("Menu.Taxpayer");
    }

    @Override
    public void activate() throws BasicException {
        loadData();
    }

    private void loadData() {
        try {
            TaxpayerInfo taxpayer = (TaxpayerInfo) this.dlTaxpayer.getTaxPayerInfo().find("1");

            txtIdentification.setText(taxpayer.getIdentification());
            txtLegalName.setText(taxpayer.getLegalName());
            txtText1.setText(taxpayer.getText1());
            txtText2.setText(taxpayer.getText2());
            txtText3.setText(taxpayer.getText3());
            txtText4.setText(taxpayer.getText4());

        } catch (BasicException ex) {
            log.error(ex.getMessage());
        }

    }

    @Override
    public boolean deactivate() {
        return true;
    }

    @Override
    public JComponent getComponent() {
        return this;
    }

    @Override
    public void init(AppView app) throws BeanFactoryException {
        this.app = app;
        this.dlTaxpayer = (DataLogicTaxpayer) this.app.getBean("dev.joguenco.pos.taxpayer.DataLogicTaxpayer");
        this.tdTaxpayer = this.dlTaxpayer.getTableTaxPayer();
    }

    @Override
    public Object getBean() {
        return this;
    }

    private Object createValue() {
        Object[] taxPayer = new Object[7];

        taxPayer[0] = 1;
        taxPayer[1] = txtIdentification.getText();
        taxPayer[2] = txtLegalName.getText();
        taxPayer[3] = txtText1.getText().isEmpty() ? null : txtText1.getText();
        taxPayer[4] = txtText2.getText().isEmpty() ? null : txtText2.getText();
        taxPayer[5] = txtText3.getText().isEmpty() ? null : txtText3.getText();
        taxPayer[6] = txtText4.getText().isEmpty() ? null : txtText4.getText();

        return taxPayer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        panelEcuador = new javax.swing.JPanel();
        jPanelInformation = new javax.swing.JPanel();
        lblIdentification = new javax.swing.JLabel();
        txtIdentification = new javax.swing.JTextField();
        lblLegalName = new javax.swing.JLabel();
        txtLegalName = new javax.swing.JTextField();
        jPanelData = new javax.swing.JPanel();
        lblText1 = new javax.swing.JLabel();
        txtText1 = new javax.swing.JTextField();
        lblText2 = new javax.swing.JLabel();
        txtText2 = new javax.swing.JTextField();
        lblText3 = new javax.swing.JLabel();
        txtText3 = new javax.swing.JTextField();
        lblText4 = new javax.swing.JLabel();
        txtText4 = new javax.swing.JTextField();
        cmdOk = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 510));

        jPanelMain.setName("jPanelMain"); // NOI18N

        jPanelInformation.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInformation.setPreferredSize(new java.awt.Dimension(900, 104));

        lblIdentification.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        lblIdentification.setText(bundle.getString("label.taxid")); // NOI18N

        txtIdentification.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblLegalName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblLegalName.setText(bundle.getString("label.namem")); // NOI18N

        txtLegalName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelInformationLayout = new javax.swing.GroupLayout(jPanelInformation);
        jPanelInformation.setLayout(jPanelInformationLayout);
        jPanelInformationLayout.setHorizontalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdentification))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLegalName, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLegalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanelInformationLayout.setVerticalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentification)
                    .addComponent(lblLegalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLegalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanelData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelData.setPreferredSize(new java.awt.Dimension(900, 304));

        lblText1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblText1.setText(bundle.getString("label.taxpayer.text1")); // NOI18N

        txtText1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblText2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblText2.setText(bundle.getString("label.taxpayer.text2")); // NOI18N

        txtText2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblText3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblText3.setText(bundle.getString("label.taxpayer.text3")); // NOI18N

        txtText3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblText4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblText4.setText(bundle.getString("label.taxpayer.text4")); // NOI18N

        txtText4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelDataLayout = new javax.swing.GroupLayout(jPanelData);
        jPanelData.setLayout(jPanelDataLayout);
        jPanelDataLayout.setHorizontalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtText1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtText4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText4)
                    .addComponent(lblText1)
                    .addComponent(lblText2)
                    .addComponent(txtText2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtText3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDataLayout.setVerticalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblText3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblText4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelEcuadorLayout = new javax.swing.GroupLayout(panelEcuador);
        panelEcuador.setLayout(panelEcuadorLayout);
        panelEcuadorLayout.setHorizontalGroup(
            panelEcuadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEcuadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEcuadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEcuadorLayout.setVerticalGroup(
            panelEcuadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEcuadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        cmdOk.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmdOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/ok.png"))); // NOI18N
        cmdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEcuador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addComponent(cmdOk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(panelEcuador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdOk, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOkActionPerformed
        ErrorMessage validate = validateData();

        if (validate.getIsError()) {
            JOptionPane.showMessageDialog(this, validate.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Object taxPayer = createValue();
            int status = this.tdTaxpayer.getUpdateSentence().exec(taxPayer);

            if (status > 0) {
                JOptionPane.showMessageDialog(this, "Se guardó con éxito",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se guardó con éxito",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (BasicException ex) {
            log.error(ex.getMessage());
        }
    }//GEN-LAST:event_cmdOkActionPerformed

    private ErrorMessage validateData() {

        if ("EC".equals(this.country) && txtIdentification.getText().trim().isEmpty()) {
            return new ErrorMessage(AppLocal.getIntString("message.identification"));
        }

        if ("EC".equals(this.country) && txtLegalName.getText().trim().isEmpty()) {
            return new ErrorMessage(AppLocal.getIntString("message.name"));
        }

        if ("EC".equals(this.country)) {
            if (txtIdentification.getText().length() != 13) {
                return new ErrorMessage(AppLocal.getIntString("message.identification.validate"));
            }
        }
        
        if ("EC".equals(this.country)) {
            if (!"SI".equals(txtText1.getText()) && !"NO".equals(txtText1.getText())) {
                return new ErrorMessage(AppLocal.getIntString("message.account.forced"));
            }
        }

        return new ErrorMessage();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdOk;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JPanel jPanelInformation;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JLabel lblIdentification;
    private javax.swing.JLabel lblLegalName;
    private javax.swing.JLabel lblText1;
    private javax.swing.JLabel lblText2;
    private javax.swing.JLabel lblText3;
    private javax.swing.JLabel lblText4;
    private javax.swing.JPanel panelEcuador;
    private javax.swing.JTextField txtIdentification;
    private javax.swing.JTextField txtLegalName;
    private javax.swing.JTextField txtText1;
    private javax.swing.JTextField txtText2;
    private javax.swing.JTextField txtText3;
    private javax.swing.JTextField txtText4;
    // End of variables declaration//GEN-END:variables

}
