/*
 * Copyright (C) 2025 Jorge Luis
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package com.unicenta.pos.panels;

import com.unicenta.basic.BasicException;
import com.unicenta.data.gui.MessageInf;
import com.unicenta.data.loader.Datas;
import com.unicenta.data.loader.SerializerWriteBasic;
import com.unicenta.data.loader.Session;
import com.unicenta.data.loader.StaticSentence;
import com.unicenta.pos.forms.AppLocal;
import com.unicenta.pos.forms.AppView;
import com.unicenta.pos.forms.BeanFactoryApp;
import com.unicenta.pos.forms.BeanFactoryException;
import com.unicenta.pos.forms.DataLogicSystem;
import com.unicenta.pos.forms.JPanelView;
import com.unicenta.pos.printer.TicketParser;
import com.unicenta.pos.printer.TicketPrinterException;
import com.unicenta.pos.scripting.ScriptEngine;
import com.unicenta.pos.scripting.ScriptException;
import com.unicenta.pos.scripting.ScriptFactory;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.UUID;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lombok.extern.slf4j.Slf4j;
import dev.resolvedor.util.Read;

/**
 *
 * @author Jorge Luis
 * @web https://resolvedor.dev
 * @mail jorgeluis@resolvedor.dev
 */
@Slf4j
public class CloseCash extends JPanel implements JPanelView, BeanFactoryApp {

    private AppView app;
    private DataLogicSystem m_dlSystem;
    private PaymentsModel m_PaymentsToClose;
    private TicketParser m_TTP;
    private Session s;
    private Connection con;
    private Statement stmt;
    private Integer result;
    private Integer dresult;
    private String SQL;
    private ResultSet rs;

    public CloseCash() {
        initComponents();
    }

    @Override
    public String getTitle() {
        return AppLocal.getIntString("Menu.CloseTPV");
    }

    @Override
    public void activate() throws BasicException {
        loadData();
    }

    @Override
    public boolean deactivate() {
        return true;
    }

    @Override
    public JComponent getComponent() {
        return this;
    }

    @Override
    public void init(AppView app) throws BeanFactoryException {
        this.app = app;
        m_dlSystem = (DataLogicSystem) this.app.getBean("com.unicenta.pos.forms.DataLogicSystem");
        m_TTP = new TicketParser(this.app.getDeviceTicket(), m_dlSystem);
    }

    @Override
    public Object getBean() {
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCashCollected = new javax.swing.JLabel();
        txtCashCollected = new javax.swing.JTextField();
        cmdCloseCash = new javax.swing.JButton();

        lblCashCollected.setText("Cash Collected");

        txtCashCollected.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cmdCloseCash.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmdCloseCash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/calculator.png"))); // NOI18N
        cmdCloseCash.setText(AppLocal.getIntString("button.closecash")); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        cmdCloseCash.setToolTipText(bundle.getString("tooltip.btn.closecash")); // NOI18N
        cmdCloseCash.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdCloseCash.setIconTextGap(2);
        cmdCloseCash.setInheritsPopupMenu(true);
        cmdCloseCash.setMaximumSize(new java.awt.Dimension(85, 33));
        cmdCloseCash.setMinimumSize(new java.awt.Dimension(85, 33));
        cmdCloseCash.setPreferredSize(new java.awt.Dimension(150, 45));
        cmdCloseCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCashCollected)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdCloseCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCashCollected))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCashCollected)
                    .addComponent(txtCashCollected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmdCloseCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCloseCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseCashActionPerformed

        Double cashCollected = Read.currency(txtCashCollected.getText());

        if (cashCollected == null) {
            JOptionPane.showMessageDialog(this, AppLocal.getIntString("value.error"), AppLocal.getIntString("label.currency"), JOptionPane.WARNING_MESSAGE);
            return;
        }

        int res = JOptionPane.showConfirmDialog(this,
                AppLocal.getIntString("message.wannaclosecash"),
                AppLocal.getIntString("message.title"),
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (res == JOptionPane.YES_OPTION) {

            try {
                //Fire cash.closed event
                ScriptEngine scriptEngine = ScriptFactory.getScriptEngine(ScriptFactory.BEANSHELL);
                DataLogicSystem dlSystem = (DataLogicSystem) app.getBean("com.unicenta.pos.forms.DataLogicSystem");
                String script = dlSystem.getResourceAsXML("cash.close");
                scriptEngine.eval(script);
            } catch (Exception e) {
                log.error("Error firing cash close event {}", e.getMessage());
            }

            Date dNow = new Date();

            try {

                if (app.getActiveCashDateEnd() == null) {
                    StaticSentence staticSentence = new StaticSentence(
                            app.getSession(),
                            "UPDATE closedcash "
                            + "SET DATEEND = ?, "
                            + "NOSALES = ? ,"
                            + "CASH_COLLECTED = ? "
                            + "WHERE HOST = ? "
                            + "AND MONEY = ?",
                            new SerializerWriteBasic(
                                    Datas.TIMESTAMP, Datas.INT, Datas.DOUBLE, Datas.STRING, Datas.STRING
                            )
                    );

                    staticSentence.exec(
                            dNow,
                            result,
                            cashCollected,
                            app.getProperties().getHost(),
                            app.getActiveCashIndex()
                    );
                }
            } catch (Exception e) {
                MessageInf msg = new MessageInf(MessageInf.SGN_NOTICE, AppLocal.getIntString("message.cannotclosecash"), e);
                msg.show(this);
            }

            try {
                // Creamos una nueva caja
                app.setActiveCash(UUID.randomUUID().toString(),
                        app.getActiveCashSequence() + 1, dNow, null);

                // creamos la caja activa
                m_dlSystem.execInsertCash(
                        new Object[]{app.getActiveCashIndex(),
                            app.getProperties().getHost(),
                            app.getActiveCashSequence(),
                            app.getActiveCashDateStart(),
                            app.getActiveCashDateEnd(), 0});

                m_dlSystem.execDrawerOpened(
                        new Object[]{app.getAppUserView().getUser().getName(), "Close Cash"});

                // ponemos la fecha de fin
                m_PaymentsToClose.setDateEnd(dNow);

                // print report
                printPayments("Printer.CloseCash");

                // Mostramos el mensaje
                JOptionPane.showMessageDialog(this,
                        AppLocal.getIntString("message.closecashok"),
                        AppLocal.getIntString("message.title"),
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (BasicException e) {
                MessageInf msg = new MessageInf(MessageInf.SGN_NOTICE,
                        AppLocal.getIntString("message.cannotclosecash"), e);
                msg.show(this);
            }

            if (app.getProperties().getProperty("payment.gateway").equals("PaymentSense")) {
                System.out.println("This method is disable");
            }
        }
    }//GEN-LAST:event_cmdCloseCashActionPerformed

    private void printPayments(String report) {

        String sresource = m_dlSystem.getResourceAsXML(report);
        if (sresource == null) {
            MessageInf msg = new MessageInf(MessageInf.SGN_WARNING,
                    AppLocal.getIntString("message.cannotprintticket"));
            msg.show(this);
        } else {
            try {
                ScriptEngine script = ScriptFactory.getScriptEngine(ScriptFactory.VELOCITY);
                script.put("payments", m_PaymentsToClose);
                script.put("nosales", result.toString());
                m_TTP.printTicket(script.eval(sresource).toString());
            } catch (ScriptException | TicketPrinterException e) {
                MessageInf msg = new MessageInf(MessageInf.SGN_WARNING,
                        AppLocal.getIntString("message.cannotprintticket"), e);
                msg.show(this);
            }
        }
    }

    private void loadData() throws BasicException {

        txtCashCollected.setEnabled(false);
        cmdCloseCash.setEnabled(false);

        // LoadData
        m_PaymentsToClose = PaymentsModel.loadInstance(app);

        // Populate Data
        m_PaymentsToClose.printSequence();
        m_PaymentsToClose.printDateStart();
        m_PaymentsToClose.printDateEnd();

        if (m_PaymentsToClose.getPayments() != 0
                || m_PaymentsToClose.getSales() != 0) {

            m_PaymentsToClose.printPayments();
            m_PaymentsToClose.printPaymentsTotal();

            m_PaymentsToClose.printSales();
            m_PaymentsToClose.printSalesBase();
            m_PaymentsToClose.printSalesTaxes();
            m_PaymentsToClose.printSalesTotal();

            txtCashCollected.setEnabled(true);
            cmdCloseCash.setEnabled(true);
        }

        m_PaymentsToClose.getPaymentsModel();
        m_PaymentsToClose.getSalesModel();

        // read number of no cash drawer activations
        try {
            result = 0;
            s = app.getSession();
            con = s.getConnection();

            SQL = "SELECT * "
                    + "FROM draweropened "
                    + "WHERE TICKETID = 'No Sale' AND OPENDATE > {fn TIMESTAMP('" + m_PaymentsToClose.getDateStartDerby() + "')}";

            stmt = (Statement) con.createStatement();
            rs = stmt.executeQuery(SQL);
            while (rs.next()) {
                result++;
            }
            rs = null;

            dresult = 0;
            SQL = "SELECT * "
                    + "FROM lineremoved "
                    + "WHERE REMOVEDDATE > {fn TIMESTAMP('" + m_PaymentsToClose.getDateStartDerby() + "')}";
            log.debug("close-cash sql -> {}", SQL);

            stmt = (Statement) con.createStatement();
            rs = stmt.executeQuery(SQL);
            while (rs.next()) {
                dresult++;
            }
            rs = null;
            con = null;
            s = null;
        } catch (SQLException e) {
            log.error("Got a problem here! Something to with dresult ");
            log.error(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCloseCash;
    private javax.swing.JLabel lblCashCollected;
    private javax.swing.JTextField txtCashCollected;
    // End of variables declaration//GEN-END:variables

}
